version: '3.8'

services:
  server:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE_TAG=${BASE_IMAGE_TAG}
        - USER_NAME=${USER_NAME}
        - POSTGRESQL_VERSION=${POSTGRESQL_VERSION}
    volumes:
      - etc:/etc
      - home:/home
      - var:/var
    ports:
      - ${LOCALHOST_PORT}:${EXTERNAL_PORT}
    user: ${USER_NAME}
    stdin_open: true
    tty: true

volumes:
  etc:
    name: ${VOLUME_NAME}_etc
  home:
    name: ${VOLUME_NAME}_home
  var:
    name: ${VOLUME_NAME}_var

networks:
  default:
    name: ${NETWORK_NAME}
